apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  labels:
    app: url-shortener
type: Opaque
stringData:
  POSTGRES_USER: "url_user"
  POSTGRES_PASSWORD: "url_password"
  POSTGRES_DB: "urlshortener"
